export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';

export const MORE_INFO_CLICKED = 'MORE_INFO_CLICKED';
